version: '3.5'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:3000
    networks:
      - film-app-server
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    networks:
      - film-app-server
networks:
  film-app-server:

